name = "model name"

[inputs]
value = 0

[[steps]]
name = "step 1"
run = """
print("step 1")
"""

[[steps]]
name = "step 2"

[[steps.branches]]
name = "branch 1"
if = '${ $("value") > 100 }'
run = """
print("branch 1");
"""

[[steps.branches]]
name = "branch 2"
if = '${ $("value") <= 100 }'

[[steps.branches.steps]]
name = "step 3"
run = """
print("branch 2")
"""
