# From https://mlflow.org/docs/latest/recipes.html#template-structure
# Adapted from https://github.com/mlflow/recipes-regression-template/blob/d0db2d9/recipe.yaml

recipe = "regression/v1"
target_col = "fare_amount"
primary_metrics = "root_mean_squared_error"

[steps]
ingest = "${INGEST_CONFIG}"

[steps.split]
split_ratios = "${SPLIT_RATIOS|default([0.75, 0.125, 0.125])}"

[steps.transform]
using = "custom"
transformer_method = "transformer_fn"

[steps.train]
using = "custom"
estimator_method = "estimator_fn"

[[steps.evaluate.validation_criteria]]
metric = "root_mean_squared_error"
threshold = 10

[[steps.evaluate.validation_criteria]]
metric = "weighted_mean_squared_error"
threshold = 20

[steps.register]
allow_non_validated_model = false

[[custom_metrics]]
name = "weighted_mean_squared_error"
function = "weighted_mean_squared_error"
greater_is_better = false
